CREATE DATABASE QL_OnlineMarket;
go

use QL_OnlineMarket;
go

create table DanhMuc
(
	MADM int primary key,
	TENDM nvarchar(100) NOT NULL
);
go

CREATE TABLE KHUYENMAI (
    MAKM INT IDENTITY(1,1) PRIMARY KEY,
    TENKM NVARCHAR(100),
    MOTA NVARCHAR(255),
    PHANTRAMGIAM INT CHECK (PHANTRAMGIAM BETWEEN 1 AND 100), 
    NGAYBATDAU DATETIME,
    NGAYKETTHUC DATETIME,            
    TRANGTHAI NVARCHAR(30) DEFAULT N'Đang áp dụng'
);
GO

CREATE TABLE SanPham (
	MASP INT IDENTITY(1001,1) PRIMARY KEY,
    TENSP NVARCHAR(100) NOT NULL,
    MOTA NVARCHAR(MAX),
    GIA DECIMAL(18,2) DEFAULT 0,
    SOLUONGTON INT DEFAULT 0,
    DONVITINH NVARCHAR(20) DEFAULT N'Cái',
    URL_ANH VARCHAR(255),
    NGAYTHEM DATETIME DEFAULT GETDATE(),
    TRANGTHAI NVARCHAR(30) DEFAULT N'Còn hàng',
    LUOTMUA INT DEFAULT 0,
    MADM INT,
    MAKM INT NULL,
    FOREIGN KEY (MADM) REFERENCES DanhMuc(MADM),
    FOREIGN KEY (MAKM) REFERENCES KhuyenMai(MAKM)
);
GO

CREATE TABLE NguoiDung (
	MAND INT IDENTITY(1, 1) PRIMARY KEY,
	TENDANGNHAP VARCHAR(50) UNIQUE,
	MATKHAU NVARCHAR(255),
	HOTEN NVARCHAR(50),
	SODIENTHOAI VARCHAR(15),
	EMAIL VARCHAR(50) UNIQUE,
	DIACHI NVARCHAR(200),
	VAITRO NVARCHAR(20) NOT NULL DEFAULT N'Khách hàng'
);
GO

CREATE TABLE DonHang
(
	MADH INT IDENTITY(100001,1) PRIMARY KEY,
	NGAYDAT DATETIME DEFAULT GETDATE(),
    NGAYGIAOHANGDK DATETIME NULL,
    TONGTIEN DECIMAL(18,0),
    PHIVANCHUYEN DECIMAL(18,0) DEFAULT 0,
    PHUONGTHUCTHANHTOAN NVARCHAR(50),
    DIACHIGIAOHANG NVARCHAR(255),
    TENNGUOINHAN NVARCHAR(100),
    SDTNGUOINHAN VARCHAR(15),
    TRANG_THAI NVARCHAR(50) DEFAULT N'Chờ xử lý',
    GHI_CHU NVARCHAR(255),
    MAND INT,
	MaKM INT,
    FOREIGN KEY (MAND) REFERENCES NGUOIDUNG(MAND),
	FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM)
);
GO

CREATE TABLE ChiTietDonHang (
	MADH INT,
	MASP INT,
	SOLUONG INT CHECK (SOLUONG > 0),
	THANHTIEN DECIMAL(18,2),
	CONSTRAINT PK_CHITIETDH PRIMARY KEY (MADH, MASP),
	FOREIGN KEY (MADH) REFERENCES DonHang(MADH),
	FOREIGN KEY (MASP) REFERENCES SanPham(MASP)
);
GO

CREATE TABLE GioHang (
	MAGH INT IDENTITY(1,1) PRIMARY KEY,
    MAND INT,
    MASP INT,
    SOLUONG INT DEFAULT 1 CHECK (SOLUONG > 0),
    NGAYTHEM DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (MAND) REFERENCES NguoiDung(MAND),
    FOREIGN KEY (MASP) REFERENCES SanPham(MASP)
);
GO

CREATE TABLE DanhGia (
    MADG INT IDENTITY(1,1) PRIMARY KEY,
    MAND INT,                        
    MASP INT,                        
    SOSAO INT CHECK (SOSAO BETWEEN 1 AND 5), 
    NOIDUNG NVARCHAR(500),           
    NGAYDANHGIA DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (MAND) REFERENCES NguoiDung(MAND),
    FOREIGN KEY (MASP) REFERENCES SanPham(MASP),
    CONSTRAINT UQ_DanhGia UNIQUE (MAND, MASP)
);

GO

