//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int MADG { get; set; }
        public Nullable<int> MAND { get; set; }
        public Nullable<int> MASP { get; set; }
        public Nullable<int> SOSAO { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> NGAYDANHGIA { get; set; }
        public string HINHANH { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
