//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int MADH { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.DateTime> NGAYGIAOHANGDK { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<decimal> PHIVANCHUYEN { get; set; }
        public string PHUONGTHUCTHANHTOAN { get; set; }
        public string DIACHIGIAOHANG { get; set; }
        public string TENNGUOINHAN { get; set; }
        public string SDTNGUOINHAN { get; set; }
        public string TRANG_THAI { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<int> MAND { get; set; }
        public Nullable<int> MaKM { get; set; }
        public string HINHTHUCGIAOHANG { get; set; }
        public string HoTenNhanHang { get; set; }
        public string TinhThanh { get; set; }
        public string QuanHuyen { get; set; }
        public string PhuongXa { get; set; }
        public string HinhThucThanhToan { get; set; }
        public string PhuongThucGiaoHang { get; set; }
        public Nullable<decimal> PhiGiaoHang { get; set; }
        public Nullable<decimal> TongThanhToan { get; set; }
        public string TrangThaiChiTiet { get; set; }

        // Thêm các properties mới
        public Nullable<decimal> DISCOUNT_AMOUNT { get; set; }
        public string DISCOUNT_CODE { get; set; }

        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
