//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public KHUYENMAI()
        {
            this.DonHangs = new HashSet<DonHang>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MAKM { get; set; }
        public string TENKM { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> PHANTRAMGIAM { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public string TRANGTHAI { get; set; }

        public Nullable<int> SOLANSUDUNG { get; set; }

        // Thêm các properties m?i (n?u ch?a có)
        public string LOAI { get; set; } // Percentage, Fixed, Freeship
        public Nullable<decimal> GIATRIGIAM { get; set; } // Giá tr? gi?m c? ??nh
        public Nullable<decimal> GIATRITOIDA { get; set; } // Giá tr? t?i ?a ???c gi?m
        public Nullable<decimal> DIEUKIENAPDUNG { get; set; } // ?i?u ki?n áp d?ng (s? ti?n t?i thi?u)
       
        public Nullable<int> SOLANDASUDUNG { get; set; } // S? l?n ?ã s? d?ng

        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
