//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.DanhGias = new HashSet<DanhGia>();
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public string MOTA { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public string DONVITINH { get; set; }
        public string URL_ANH { get; set; }
        public Nullable<System.DateTime> NGAYTHEM { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<int> LUOTMUA { get; set; }
        public Nullable<int> MADM { get; set; }
        public Nullable<int> MAKM { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
    }
}
